In [ ]:
!pip list | grep numpy    # 윈도우에서는 grep 을 findstr 명령어 사용

numpy                                 2.0.2


In [ ]:
import numpy as np    # np.함수명 또는 np.클래스명
# from numpy import 함수, 클래스 등등
# ↪ 함수 또는 클래스명만 직접 사용

### 스칼라
- 하나의 숫자. 차원이 없는 값. `x = np.array(5)`

In [ ]:
# 넘파이 배열 생성하는 방법
# np.array() 메소드로 생성 -> 데이터의 차원에 따라 부르는 용어
scalar = np.array(5)
print('scalar :',scalar)
print('type(scalar) :',type(scalar))

# ndim - 차원을 구하는 속성 : 0 -> 스칼라
print('scalar.ndim :',scalar.ndim)

# shape - 넘파이 배열의 모양
print('scalar.shape :',scalar.shape)

scalar : 5
type(scalar) : <class 'numpy.ndarray'>
scalar.ndim : 0
scalar.shape : ()


### 백터
- 1차원 배열. 여러 개의 스칼라가 나열된 형태. `v = np.array([1, 2, 3])`

In [ ]:
# 리스트를 넘파이 배열로 생성
# 길이가 4인 벡터
ndarr1 = np.array([1,2,3,4])
print('ndarr1 =',ndarr1)
print('type(ndarr1) :',type(ndarr1))
print('ndarr1.ndim :',ndarr1.ndim)    # 1차원 : 벡터
print('ndarr1.shape :',ndarr1.shape)  # (4. ) : 4는 배열의 첫 번째 축(axis 0)의 크기

ndarr1 = [1 2 3 4]
type(ndarr1) : <class 'numpy.ndarray'>
ndarr1.ndim : 1
ndarr1.shape : (4,)


- 넘파이 정수 타입 : `numpy.int64` (기본이 64비트)

In [ ]:
print('type(ndarr1) :',type(ndarr1))          # <class 'numpy.ndarray'> -> 넘파이 배열 클래스 타입
print('type(ndarr1[0]) :',type(ndarr1[0]))    # <class 'numpy.int64'> -> 넘파이 정수 타입 (기본이 64비트)
print('type(ndarr1[1]) :',type(ndarr1[1]))
print('type(ndarr1[2]) :',type(ndarr1[2]))
print('type(ndarr1[3]) :',type(ndarr1[3]))

type(ndarr1) : <class 'numpy.ndarray'>
type(ndarr1[0]) : <class 'numpy.int64'>
type(ndarr1[1]) : <class 'numpy.int64'>
type(ndarr1[2]) : <class 'numpy.int64'>
type(ndarr1[3]) : <class 'numpy.int64'>


- 열 벡터 (n행 1열)

In [ ]:
 # 열벡터 (nx1): 행렬이지만 벡터처럼 취급 가능
 # n = 3
col_vector = np.array([[10],
                      [20],
                      [30]])
print('col_vector =')
print(col_vector)
print('col_vector.ndim :',col_vector.ndim)
print('col_vector.shape :',col_vector.shape)

col_vector =
[[10]
 [20]
 [30]]
col_vector.ndim : 2
col_vector.shape : (3, 1)


- 행 벡터 (1열n행)

In [ ]:
 # 행벡터 (1 x n) :
 # n= 3
row_vector = np.array([[1,2,3]])
print('row_vector =',row_vector)
print('row_vector.ndim :',row_vector.ndim)
print('row_vector.shape :',row_vector.shape)

row_vector = [[1 2 3]]
row_vector.ndim : 2
row_vector.shape : (1, 3)


### 행렬 (matrix)
- 2차원 배열. 벡터들이 행과 열로 구성된 형태

In [ ]:
# matrix (행렬) : 2차원 배열 . m행 n열(m x n 행렬)
# matrix = np.array([[1,2],[4,5,6]])   # 오류
matrix = np.array([[1,2,3],[4,5,6]])
print('matrix =')
print(matrix)
print('matrix.ndim :',matrix.ndim)     # 2차원
print('matrix.shape :',matrix.shape)   # 2행 3열
# shape 은 (2,3) 튜플을 리턴
# 행(axis=0)의 크기, 열(axis= 1)의 크기 -> 축의 크기)

matrix =
[[1 2 3]
 [4 5 6]]
matrix.ndim : 2
matrix.shape : (2, 3)


### 텐서
- 3차원 이상 배열. 행렬을 여러층으로 쌓은 형태

In [ ]:
tensor = np.array([[[1,2,3,4],[4,5,6,5]],
                   [[7,8,9,1],[10,11,12,4]],
                   [[13,14,15,5],[16,17,18,6]]])
# 2 x 4 행렬이 3개
print('tensor =')
print(tensor)
print('tensor.ndim :',tensor.ndim)
print('tensor.shape :',tensor.shape)   # (3,2,4)   len가 4인 1차원 배열이 2개, 2 x 4 행렬이 3개
# (행(axis=1)의 크기, 열(axis= 2)의 크기 -> 축의 크기)
# 2x4 행렬이 3개. 가장 바깥쪽 축이 axis=0
# shape 은 (3, 2, 4) 튜플을 리턴. ** 튜플의 인덱스와 axis 값이 같다. **

tensor =
[[[ 1  2  3  4]
  [ 4  5  6  5]]

 [[ 7  8  9  1]
  [10 11 12  4]]

 [[13 14 15  5]
  [16 17 18  6]]]
tensor.ndim : 3
tensor.shape : (3, 2, 4)


- 예시 코드

In [ ]:
import numpy as np

# 스칼라
a = np.array(5)           # shape: ()

# 벡터
b = np.array([1, 2, 3])   # shape: (3,)

# 행렬
c = np.array([[1, 2], [3, 4]])  # shape: (2, 2)

# 3차원 텐서
d = np.array([[[1], [2]], [[3], [4]]])  # shape: (2, 2, 1)

- 리스트를 ndarray 로 변환 : `ndarr1 = np.array(list1)`

In [ ]:
# 리스트를 ndarray로 변환
list1 = [1, 2, 3, 4]
print('list1 =',list1)
print('type(list1) :',type(list1))

list1 = [1, 2, 3, 4]
type(list1) : <class 'list'>


In [ ]:
ndarr1 = np.array(list1)
print('ndarr1 =',ndarr1)
print('type(ndarr1) :',type(ndarr1))

ndarr1 = [1 2 3 4]
type(ndarr1) : <class 'numpy.ndarray'>


- ndarray 를 리스트로 변환 : `list2 = ndarr1.tolist()`

In [ ]:
# ndarray를 리스트로 변환
list2 = ndarr1.tolist()
print('list2 =',list2)
print('type(list2) :',type(list2))

list2 = [1, 2, 3, 4]
type(list2) : <class 'list'>


### 넘파이 배열생성

In [ ]:
# 💥넘파이 배열을 만들 때
# ↪ 리스트, 튜플, range(값) -> sequence 자료형으로 넘파이 배열 생성

In [ ]:
# 넘파이 배열 생성 메소드1
# np.zeros((2, 3))     # 2x3 배열, 모든 값 실수 0
np.zeros((2, 3),dtype=int)     # 2x3 배열, 모든 값 실수 0

array([[0, 0, 0],
       [0, 0, 0]])

In [ ]:
# 넘파이 배열 생성 메소드 3
np.ones((2, 3))     # 2x3 배열, 모든 값 실수 1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# 넘파이 배열 생성 메소드 3
# 모든 원소값을 지정된 값으로 하기
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [ ]:
# 참고 : 튜플로 생성하는 넘파이 배열
test = np.array(((2,3,4),(4,5,6)))
print(test.shape)
test

(2, 3)


array([[2, 3, 4],
       [4, 5, 6]])

### 자동 변환
- 요소의 데이터 타입이 서로 다른 리스트를 넘파이로 변환할 때
- 넘파이(Numpy) 배열의 요소들은 모두 같은 데이터타입(dtype)을 가져야하므로 포괄적인 타입으로 자동 변환

In [ ]:
list1 = [1, 3.14, 'Python', '😊', True]
print(list1)
print(type(list1))
print(type(list1[0]))
print(type(list1[1]))
print(type(list1[2]))
print(type(list1[3]))
print(type(list1[4]))

In [ ]:
ndtest = np.array(list1)        # 원소의 데이터 타입이 같아야 하므로 모두 문자열로 변환
print(ndtest)
print(type(ndtest[0]))          # <class 'numpy.str_'>

In [ ]:
list2 = [1, 3.14, True]
ndtest = np.array(list2)        # 원소의 데이터 타입이 같아야 하므로 모두 실수로 변환
print(ndtest[0])
print(ndtest[1])
print(ndtest[2])
print(type(ndtest[0]))          # <class 'numpy.float64'>

- 자동 변환하지 않고 직접 타입 지정
- dtype는 "data type". 넘파이 배열의 원소들이 어떤 자료형인지를 나타내는 속성

In [ ]:
# dtype 속성으로 변환을 하려는 타입 지정
ndarr3 = np.array([1, 2, 3.64, True], dtype=int)
# int는 파이썬 타입 -> 파이썬 타입으로 변환
print(ndarr3)

[1 2 3 1]


In [ ]:
ndarr4 = np.array(['1', 2, 3.14, True], dtype=int)
print(ndarr4)

[1 2 3 1]


In [ ]:
# int로 변환 못하는 'a' 때문에 오류
ndarr4 = np.array(['a', 2, 3.14, True], dtype=int)
print(ndarr4)

### ndarray 인덱싱과 슬라이싱

In [ ]:
ndarr1 = np.array(['🍓', '🍉', '🍌', '🍒', '🍑'])
print('ndarr1 =',ndarr1)
print('ndarr1.shape :',ndarr1.shape)   # 해당 배열의 크기를 나타내는 튜플

ndarr1 = ['🍓' '🍉' '🍌' '🍒' '🍑']
ndarr1.shape : (5,)


- 인덱싱

In [ ]:
# 인덱싱
print('ndarr1[0] =',ndarr1[0])
print('ndarr1[4] =',ndarr1[4])
print('ndarr1[-1] =',ndarr1[-1])
print('ndarr1[-2] =',ndarr1[-2])
print('type(ndarr1[0]) :',type(ndarr1[0]))

ndarr1[0] = 🍓
ndarr1[4] = 🍑
ndarr1[-1] = 🍑
ndarr1[-2] = 🍒
type(ndarr1[0]) : <class 'numpy.str_'>


- 슬라이싱

In [ ]:
# 슬라이싱 - 새로운 ndarray 를 리턴.
print('ndarr1[0:3] =',ndarr1[0:3])
print('ndarr1[2:] =',ndarr1[2:])
print('ndarr1[:3] =',ndarr1[:3])
print('type(ndarr1[0:3]) :',type(ndarr1[0:3]))   # 1차원 배열을 슬라이싱하면 1차원 리턴

ndarr1[0:3] = ['🍓' '🍉' '🍌']
ndarr1[2:] = ['🍌' '🍒' '🍑']
ndarr1[:3] = ['🍓' '🍉' '🍌']
type(ndarr1[0:3]) : <class 'numpy.ndarray'>


- 2차원 배열 (행렬) : `ndarr2d[row_start:row_end:row_step, col_start:col_end:col_step]`

In [ ]:
# 2차원 배열
ndarr2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11,12]])
print('ndarr2d =')
print(ndarr2d)
print('ndarr2d.shape :',ndarr2d.shape)   # (3,4)

ndarr2d =
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
ndarr2d.shape : (3, 4)


`0 은 인덱싱
: 는 슬라이싱`

- `ndarr2d[0,:]` 는 0 행만 추출하는 슬라이싱. 결과는 벡터

In [ ]:
# 0행의 모든 요소 가져오기 - 아래 3가지 방법 모두 가능함.
print('ndarr2d[0,:] =',ndarr2d[0,:])
print('ndarr2d[0,] =',ndarr2d[0,])
print('ndarr2d[0] =',ndarr2d[0])
print('ndarr2d[0].shape :',ndarr2d[0].shape)   # 2차원 배열에서 행만 가져오면 1차원

ndarr2d[0,:] = [1 2 3 4]
ndarr2d[0,] = [1 2 3 4]
ndarr2d[0] = [1 2 3 4]
ndarr2d[0].shape : (4,)


- `ndarr2d[:,0]` 는 0 열만 추출하는 슬라이싱. 결과는 벡터

In [ ]:
# 0열 가져오기 - 새로운 넘파이 배열 생성함.
print('ndarr2d[:,0] =',ndarr2d[:,0])
result = ndarr2d[:,0]
print('result =',result)
print('result.shape :',result.shape)    # 2차원 배열에서 열만 가져오면 1차원

ndarr2d[:,0] = [1 5 9]
result = [1 5 9]
result.shape : (3,)


- `ndarr2d[:,-1]` 는 모든 행에서 마지막 열만 추출하는 슬라이싱. 결과는 벡터

In [ ]:
print('ndarr2d[:, -1] =',ndarr2d[:, -1])
print('ndarr2d[..., ::-1] =')
print(ndarr2d[..., ::-1])
print('ndarr2d[..., -1] =',ndarr2d[..., -1])    # Ellipsis

ndarr2d[:, -1] = [ 4  8 12]
ndarr2d[..., ::-1] =
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
ndarr2d[..., -1] = [ 4  8 12]


In [ ]:
# ndarr2d[::-1]  행만 슬라이싱이고 -1 step 이므로 행의 순서를 역순
# ndarr2d[::-1, :] 에서 열 지정이 생략된 형식.(행 슬라이싱에서만 생략 가능)

In [ ]:
print('ndarr2d[::-1] =')
print(ndarr2d[::-1])
print('ndarr2d[::-1, :] =')
print(ndarr2d[::-1, :])

ndarr2d[::-1] =
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
ndarr2d[::-1, :] =
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [ ]:
# 퀴즈 : 열의 순서만 역순으로 하고 싶다면
ndarr2d[:,::-1]

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

### 다양한 예시

- tensor (3차원 배열) 슬라이싱

In [ ]:
# 1️⃣ 순수한 인덱싱 : shape (3, 2, 4)  => 스칼라
# 2️⃣ 순순한 슬라이싱
# 3️⃣ 혼합

In [ ]:
tensor = np.array([[[1,2,3,4],[4,5,6,5]],
                   [[7,8,9,1],[10,11,12,4]],
                   [[13,14,15,5],[16,17,18,6]]])
print('tensor.shape :',tensor.shape)
tensor

tensor.shape : (3, 2, 4)


array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  5]],

       [[ 7,  8,  9,  1],
        [10, 11, 12,  4]],

       [[13, 14, 15,  5],
        [16, 17, 18,  6]]])

In [ ]:
# 1️⃣ 순수한 인덱싱 : shape (3, 2, 4)  => 스칼라
tensor[2,1,3]

np.int64(6)

In [ ]:
# 2️⃣ 순수한 슬라이싱 : 차원이 변경되지 않는다.
tensor[:,:,::-1]

array([[[ 4,  3,  2,  1],
        [ 5,  6,  5,  4]],

       [[ 1,  9,  8,  7],
        [ 4, 12, 11, 10]],

       [[ 5, 15, 14, 13],
        [ 6, 18, 17, 16]]])

In [ ]:
# 3️⃣ 혼합 => 결과 배열은 차원 축소
tensor[0,1,:]
tensor[0,1]   # axis=2 모든 것(생략가능)

array([4, 5, 6, 5])

In [60]:
# axis=0 의 모든 행의 3번째 열
tensor[0,:,2]

array([3, 6])

In [61]:
# 아래 3개가 모두 같은 결과(의미)
# axis=0 의 모든 배열 가져오기
tensor[0,:,:]
tensor[0, ...]
tensor[0]

array([[1, 2, 3, 4],
       [4, 5, 6, 5]])

In [62]:
# 모든 axis 에서 두번째 행 모든 열 가져오기
tensor[:,1,:]

array([[ 4,  5,  6,  5],
       [10, 11, 12,  4],
       [16, 17, 18,  6]])

In [63]:
# 다차원 배열에서는 ...(생략기호, ellipsis) 사용
# tensor[:,:,::-1]  또는 tensor[0,:,:] 에서 앞 또는 뒤의 모든 축 모든 값으로 지정
# 그러나, tensor[0,:,:] 는 tensor[0] 으로 생략하는 형식이 더 많이 쓰입니다.
tensor[... , ::-1]

array([[[ 4,  3,  2,  1],
        [ 5,  6,  5,  4]],

       [[ 1,  9,  8,  7],
        [ 4, 12, 11, 10]],

       [[ 5, 15, 14, 13],
        [ 6, 18, 17, 16]]])

In [65]:
tensor2 = np.array([[[1,2,3,4],[4,5,6,5],[14,15,16,15]],
                   [[7,8,9,1],[10,11,12,4],[20,21,22,24]],
                   [[13,14,15,5],[16,17,18,6],[36,37,38,36]],
                   [[3,4,5,5],[6,7,8,6],[6,7,8,6]],
                    ])
print('tensor2.shape :',tensor2.shape)
tensor2

tensor2.shape : (4, 3, 4)


array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  5],
        [14, 15, 16, 15]],

       [[ 7,  8,  9,  1],
        [10, 11, 12,  4],
        [20, 21, 22, 24]],

       [[13, 14, 15,  5],
        [16, 17, 18,  6],
        [36, 37, 38, 36]],

       [[ 3,  4,  5,  5],
        [ 6,  7,  8,  6],
        [ 6,  7,  8,  6]]])

In [67]:
# axis=1 과 axis=2 에서 2~3 번째 행 모든 열
tensor2[1:3,1:3,0:3]

array([[[10, 11, 12],
        [20, 21, 22]],

       [[16, 17, 18],
        [36, 37, 38]]])

In [71]:
# 정수 배열 인덱싱 : 인덱스를 여러개 지정하기
# 가져오고 싶은 인덱스를 배열 또는 리스트로 전달

# 리스트 1차원 배열
ndarr2 = np.array([10, 15, 2, 8, 20, 90, 85, 44, 23, 32])
print('ndarr2 =',ndarr2)

#  1차원 배열을 대상으로 가져올 인덱스 3개 지정
print('ndarr2[[2,5,9]] =',ndarr2[[2,5,9]])
print('type(ndarr2[[2,5,9]]) :',type(ndarr2[[2,5,9]]))
#  ↪ ndarr2[2] , ndarr2[5] , ndarr2[9]
#  [2,5,9] 는 인덱스 리스트

ndarr2 = [10 15  2  8 20 90 85 44 23 32]
ndarr2[[2,5,9]] = [ 2 90 32]
type(ndarr2[[2,5,9]]) : <class 'numpy.ndarray'>


In [74]:
idx_list = [0,2,4,6,8]
ndarr2[idx_list]

array([10,  2, 20, 85, 23])

In [76]:
# 참고 : 2차원 배열의 순수한 인덱싱
print(ndarr2d[0][1])  # 0행 1열
print(ndarr2d[2][2])  # 2행 2열
print(ndarr2d[1][1])  # 1행 1열
print('------- 위와 같은 의미 -------')
print(ndarr2d[0,1])
print(ndarr2d[2,2])
print(ndarr2d[1,1])

2
11
6
------- 위와 같은 의미 -------
2
11
6


In [86]:
ndarr2d = np.array([[1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]])

# 정수 배열 인덱싱
print('ndarr2d[0][1] =',ndarr2d[0][1])   # 1 행 2 열 => 2
print('ndarr2d[2][2] =',ndarr2d[2][2])   # 3 행 3 열 => 11
print('ndarr2d[1][1] =',ndarr2d[1][1])   # 2 행 2 열 => 6
ndarr2d[[0, 2, 1],[1, 2 ,1]]

ndarr2d[0][1] = 2
ndarr2d[2][2] = 11
ndarr2d[1][1] = 6


array([ 2, 11,  6])

In [90]:
# 뒤에 열 지정안해주면 전체 열 가져오기
# ndarr2d[[0, 2, 1]]
print('ndarr2d[0] =',ndarr2d[0])
print('ndarr2d[2] =',ndarr2d[2])
print('ndarr2d[1] =',ndarr2d[1])
ndarr2d[[0, 2, 1]]

ndarr2d[0] = [1 2 3 4]
ndarr2d[2] = [ 9 10 11 12]
ndarr2d[1] = [5 6 7 8]


array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [91]:
# ndarr2d[[0, 2, 1,1], [1, 2 ,1, 3]]
print('ndarr2d[0][1] =',ndarr2d[0][1])
print('ndarr2d[2][2] =',ndarr2d[2][2])
print('ndarr2d[1][1] =',ndarr2d[1][1])
print('ndarr2d[1][3] =',ndarr2d[1][3])
ndarr2d[[0, 2, 1,1], [1, 2 ,1, 3]]

ndarr2d[0][1] = 2
ndarr2d[2][2] = 11
ndarr2d[1][1] = 6
ndarr2d[1][3] = 8


array([ 2, 11,  6,  8])