In [ ]:
# np.sum()
import numpy as np

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6]])
arr.shape

(2, 3)

In [ ]:
# axis=0 기준으로 sum
result = np.sum(arr,axis=0)
print(type(result))
result

<class 'numpy.ndarray'>


array([5, 7, 9])

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr.shape

(3, 3)

In [ ]:
# axix=0 기준으로 sum : 행을  더한다.
result = np.sum(arr,axis=0)
print(type(result))
result

<class 'numpy.ndarray'>


array([12, 15, 18])

In [ ]:
# axix=1(두번째 축) 기준으로 sum : 각 행의 열 값을  더한다.
arr = np.array([[1,2,3],
                [4,5,6]])
result = np.sum(arr,axis=1)
print(type(result))
result

<class 'numpy.ndarray'>


array([ 6, 15])

In [ ]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
arr.shape

(3, 3)

In [ ]:
result = np.sum(arr,axis=1)
print(type(result))
print(result.shape)
result

<class 'numpy.ndarray'>
(3,)


array([ 6, 15, 24])

In [ ]:
result = np.sum(arr)
print(result)

45


In [ ]:
# np.mean() : 함수인자는 sum() 함수와 동일함.
arr = np.array([[1,2,3],
                [4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
result = np.mean(arr,axis=0)
result   # sum 결과는 [5,7,9] 행 2개

array([2.5, 3.5, 4.5])

In [ ]:
result = np.mean(arr,axis=1)
result   # sum 결과는 [6.15] 열 3개

array([2., 5.])

- 요약 : shape이 (2,3) 인 행렬일 때 axis =0 이면 (3,) 행렬, axis=1 이면 (2,) 행렬 리턴

### 행렬 연산
- 사칙 연산 : +, - , * , /
- axis 기준 없음. 같은 위치의 데이터 끼리 연산. shape 이 같은 2개의 행렬만 연산가능
  + 예외적으로 기준이 맞는 경우 행렬의 브로드 캐스팅으로 연산할 수 있음.
  + ↪ shape 의 크기가 작은 배열을 큰 배열에 맞게 자동으로 확장(반복)

In [ ]:
a = np.array([[1, 2, 3],
              [2, 3, 4]])
b = np.array([[3, 4, 5],
              [1, 2, 3]])
print(a.shape, b.shape)

(2, 3) (2, 3)


- ndarry 의 shape 이 같은 두 행렬의 사칙연산

In [ ]:
# 행렬 사칙 연산 : 같은 행, 열 위치의 요소끼리 연산
# 행렬 덧셈
print(a+b)

[[4 6 8]
 [3 5 7]]


In [ ]:
# 행렬 뺄셈
print(a-b)

[[-2 -2 -2]
 [ 1  1  1]]


In [ ]:
# 행렬 원소별 곱셉
print(a*b)

[[ 3  8 15]
 [ 2  6 12]]


In [ ]:
# 행렬 나눗셈
print(a/b)

[[0.33333333 0.5        0.6       ]
 [2.         1.5        1.33333333]]


In [ ]:
# 행렬 나눗셈의 나머지
print(a%b)

[[1 2 3]
 [0 1 1]]


In [ ]:
# 행렬 나눗셈의 몫
print(a//b)

[[0 0 0]
 [2 1 1]]


In [ ]:
# 배열의 크기가 다른지만 연산이 가능한 경우
a = np.array([[1, 2, 3],
              [2, 3, 4]])
# b = np.array([[3, 4, 5]])  # 2차원
b = np.array([3,4,5])  # 1차원
print(a.shape,b.shape)

(2, 3) (3,)


In [ ]:
# shape 이 작은 배열이 확장
# b = np.array([[3, 4, 5],[3,4,5]]) 형태로 연산 수행
print(a+b)

[[4 6 8]
 [5 7 9]]


### 행렬 곱
- 벡터, 스칼라, 행렬 모두 처리 가능
- np.dot() : dot product(내적) 는 1차원 배열(벡터)의 곱셈의 합. 2차원 배열 사용 가능
- np.matmul() : 다차원 배열의 행렬 곱에 특화.
- @ 기호 : matmul(), dot() 함수와 같은 역할.

In [ ]:
# 1차원 배열의 내적(product) => 스칼라 값
#    ㄴ dot 메소드 , 기호 @
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
# 내적 연산 : 같은 위치의 값을 각각 곱해서 더하기. 수학적 의미는 벡터 간의 곱셈.
print(np.dot(a, b))   # 1x4 + 2x5 +3x6

32


In [ ]:
# 파이썬 3.5 이상 버전. 행렬 곱
print(a @ b)

32


In [ ]:
# 2차원 배열 행렬곱은 A행과 B열의 내적으로 구성된다.
ndarr3 = np.array([[1, 2, 3],
                   [2, 3, 4]])
ndarr4 = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])
print('ndarr3 =')
print(ndarr3)
print('ndarr4 =')
print(ndarr4)
print(ndarr3.shape)
print(ndarr4.shape)

# 2차원 배열에서 내적 (다차원은 더 복잡)
print((1*1 + 2*3 + 3*5), (1*2 + 2*4 + 3*6))   # ndarr3 0행 @ ndarr4 0열, ndarr3 0행 @ ndarr4 1열
print((2*1 + 3*3 + 4*5), (2*2 + 3*4 + 4*6))   # ndarr3 1행 @ ndarr4 0열, ndarr3 1행 @ ndarr4 1열

ndarr3 =
[[1 2 3]
 [2 3 4]]
ndarr4 =
[[1 2]
 [3 4]
 [5 6]]
(2, 3)
(3, 2)
22 28
31 40


In [ ]:
# 곱(product, 내적) 연산 정리
r1 = ndarr3 @ ndarr4     #
r2 = np.dot(ndarr3, ndarr4)  #
r3 = np.matmul(ndarr3, ndarr4)  # 다차원 배열에 특화한 행렬 곱(딥러닝, 텐서 연산에 적합)
# matmul : matrix multuply

print (r1)
print(type(r1))
print('--------------------------')
print (r2)
print(type(r2))
print('--------------------------')
print (r3)
print(type(r3))

[[22 28]
 [31 40]]
<class 'numpy.ndarray'>
--------------------------
[[22 28]
 [31 40]]
<class 'numpy.ndarray'>
--------------------------
[[22 28]
 [31 40]]
<class 'numpy.ndarray'>


### 요약

```
- np.dot(A,B)                    1D: 내적 / 2D: 행렬곱
- np.matmul(A,B)                 다차원 행렬곱만 수행(다차원 배열의 많은 연산횟수를 효율적으로 수행)
- A @ B                          파이썬 3.5 버전에서 dot, matmul 함수 대신에 사용하는 기호
```

```
A 행렬 : (m,n)
B 행렬 : (x,y)
A와 B의 행렬곱이 가능하려면 n과 x 값이 같아야 하고
A와 B의 행렬곱 결과는 (m,y) shape 입니다.
```

In [ ]:
# 2 x 3
ndarr3 = np.array([[1, 2, 3],
                   [2, 3, 4]])
# 2 x 2
ndarr4 = np.array([[1, 2],
                   [3, 4]])

In [ ]:
# 행렬곱
ndarr3 @ ndarr4
# 오류 : ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0

### 복습
- 넘파이 배열 만들기 : 리스트, 튜플, range() 등 시퀀스를 갖는 자료구조로 만들기
- np.array(리스트 또는 튜플 또는 range())로 설정
  + 리스트와 튜플은 다차원 가능
  + range() 함수는 1차원만 가능

### np.arange() 는 range() 함수 역할과 동일함. 다른점은 바로 넘파이 배열을 생성합니다.


### 순차적인 값 생성

In [ ]:
arr1 = range(1,11)
print('arr1 =',arr1)
print('type(arr1) :',type(arr1))
for i in arr1:
  print(i,end=' ')

arr1 = range(1, 11)
type(arr1) : <class 'range'>
1 2 3 4 5 6 7 8 9 10 

- `np.arange(start, stop, step)` 는 start 부터 stop -1 까지의 정수(또는 실수)를 일정한 간격(step) 으로 넘파이 배열 생성
- start, stop, step 는 실수값도 가능

In [ ]:
ndarr2 = np.arange(1, 11)  # array range
print('ndarr2 =',ndarr2)
print('type(ndarr2) :',type(ndarr2))
print(ndarr2.shape)  # 1차원 배열

ndarr2 = [ 1  2  3  4  5  6  7  8  9 10]
type(ndarr2) : <class 'numpy.ndarray'>
(10,)


- `np.linspace(start, end, 개수)` 는 시작과 종료값을 포함하여 개수만큼 정확한 간격으로 배열 생성함. 정밀한 실수 간격에 사용하는 메소드(lineary spaced)

In [ ]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [ ]:
np.linspace(0,1.2,6)

array([0.  , 0.24, 0.48, 0.72, 0.96, 1.2 ])

### 정렬
- sort() 함수

In [ ]:
ndarr1 = np.array([1, 10, 5, 7, 2, 4, 3, 6, 8, 9])
print('ndarr1 =',ndarr1)
result = np.sort(ndarr1)
# 오름차순 정렬하여 새로운 넘파이 배열 리턴.
print('type(result) :',type(result))
print('result =',result)          # ndarr1 은 변경안됨.

ndarr1 = [ 1 10  5  7  2  4  3  6  8  9]
type(result) : <class 'numpy.ndarray'>
result = [ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
print(result[::-1]) # 내림차순 정렬
print(np.sort(ndarr1)[::-1]) # 위와 동일

[10  9  8  7  6  5  4  3  2  1]
[10  9  8  7  6  5  4  3  2  1]


In [ ]:
# 정렬 : 2차원 행렬
ndarr2d = np.array([[11, 10, 2, 9],
                    [3, 6, 4, 2],
                    [5, 1, 7, 8]])
print(ndarr2d.shape)

(3, 4)


In [ ]:
#  axis=0 : 축이 행이므로 각 행의 같은 위치 열값에 대해 정렬
#  ㄴ 기존 행의 값(요소)가 달라짐
np.sort(ndarr2d, axis=0)

array([[ 3,  1,  2,  2],
       [ 5,  6,  4,  8],
       [11, 10,  7,  9]])

In [ ]:
#  axis=1 : 축이 열이므로 각 행 안에서 값(요소)들이 개별적으로 정렬
np.sort(ndarr2d, axis=1)

array([[ 2,  9, 10, 11],
       [ 2,  3,  4,  6],
       [ 1,  5,  7,  8]])

In [ ]:
print(ndarr2d)
np.sort(ndarr2d, axis=-1)
# 2차원 행렬에서 axis=-1 은 axis=1 과 동일
# 퀴즈 : 3차원 행렬에서 axis=-1 은 axis= 2 과 동일

[[11 10  2  9]
 [ 3  6  4  2]
 [ 5  1  7  8]]


array([[ 2,  9, 10, 11],
       [ 2,  3,  4,  6],
       [ 1,  5,  7,  8]])

### 배열의 재구성
- 1차원 배열을 다른 차원 배열로 재구성

In [ ]:
ndarr1 = np.array([1, 2, 3, 4, 5, 6])
print('ndarr1.shape :',ndarr1.shape)  # (6,) 1차원배열
ndarr2 = ndarr1.reshape(2, 3)  # (2행, 3열) 형태로 재구성
print('type(ndarr2) :',type(ndarr2))
print('ndarr2.shape :',ndarr2.shape)
ndarr2
# (1,6) (6,1) (2,3) (3,2)

ndarr1.shape : (6,)
type(ndarr2) : <class 'numpy.ndarray'>
ndarr2.shape : (2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
ndarr2 = ndarr1.reshape(1, 6)
ndarr2

array([[1, 2, 3, 4, 5, 6]])

In [54]:
ndarr2 = ndarr1.reshape(6, 1)
ndarr2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
ndarr2 = ndarr1.reshape(4, 2)
ndarr2
# 오류 : ValueError: cannot reshape array of size 6 into shape (4,2)

- 2차원 배열을 다른 차원배열로 재구성

In [55]:
ndarr3 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
print(ndarr3.shape)

(2, 4)


In [57]:
# reshape 차원은 전체 요소의 갯수는 변함 없게 합니다.
reshaped_arr =ndarr3.reshape(4,2)
print(reshaped_arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


- 3차원 배열을 다른 차원배열로 재구성

In [58]:
tensor = np.array([[[1,2,3,4],[4,5,6,5]],
                   [[7,8,9,1],[10,11,12,4]],
                   [[13,14,15,5],[16,17,18,6]]])
tensor.shape    # 3 * 2 * 4 = 24

(3, 2, 4)

In [59]:
result = tensor.reshape(2,4,3)
result

array([[[ 1,  2,  3],
        [ 4,  4,  5],
        [ 6,  5,  7],
        [ 8,  9,  1]],

       [[10, 11, 12],
        [ 4, 13, 14],
        [15,  5, 16],
        [17, 18,  6]]])

- `tensor.reshape(-1,4)` 에서 -1 은 자동 계산되는 차원을 의미. 열을 4의 크기로 맞추고 다른 차원은 자동 계산

In [60]:
# 4열의 2차원 배열로 reshape. tensor 에 저장된 값이 24. 4의 배수이므로 자동계산으로 reshape 가능함.
result = tensor.reshape(-1,4)
result

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  5],
       [ 7,  8,  9,  1],
       [10, 11, 12,  4],
       [13, 14, 15,  5],
       [16, 17, 18,  6]])

In [61]:
tensor.reshape(4,-1)

array([[ 1,  2,  3,  4,  4,  5],
       [ 6,  5,  7,  8,  9,  1],
       [10, 11, 12,  4, 13, 14],
       [15,  5, 16, 17, 18,  6]])

In [74]:
# 1차원
print(tensor.reshape(-1))
print(np.shape(tensor.reshape(-1)))

# 2차원
print(tensor.reshape(1,-1))
print(np.shape(tensor.reshape(1,-1)))

[ 1  2  3  4  4  5  6  5  7  8  9  1 10 11 12  4 13 14 15  5 16 17 18  6]
(24,)
[[ 1  2  3  4  4  5  6  5  7  8  9  1 10 11 12  4 13 14 15  5 16 17 18  6]]
(1, 24)


In [ ]:
# 24의 약수로 차원의 값을 지정해야 함.
tensor.reshape(-1, 5)  # ValueError: cannot reshape array of size 24 into shape (5)

- `nparr.transpose()` : 배열의 축(axis)의 순서를 재정렬

In [75]:
ndarr1 = np.arange(1,7)   # array range
ndarr1

array([1, 2, 3, 4, 5, 6])

In [76]:
ndarr2 = ndarr1.reshape(2,3)
ndarr2.shape

(2, 3)

In [77]:
ndarr2

array([[1, 2, 3],
       [4, 5, 6]])

In [79]:
# (2,3) 을 (3,2) 로 변환
ndarr3 = ndarr2.transpose()
ndarr3

array([[1, 4],
       [2, 5],
       [3, 6]])

- 3차원 transpose()

In [80]:
# 3차원 transpose
# 3차원 (z,y,x) 는 0,1,2 를
# (x,y,z) 2,1,0
# (y,x,z) 1,2,0
# (x,z,y) 2,0,1
# (z,x,y) 0,2,1
#   옵션은 transpose 위치를 지정 (y,x,z) 이면
#   arr1.transpose(1,2,0)

In [81]:
ndarr3 = np.arange(24).reshape(2, 3, 4)  # shape: (2, 3, 4)
ndarr3

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [82]:
transposed = ndarr3.transpose(1, 0, 2)
# z와 y축 바꾸기
# shape: (3, 2, 4)
transposed

array([[[ 0,  1,  2,  3],
        [12, 13, 14, 15]],

       [[ 4,  5,  6,  7],
        [16, 17, 18, 19]],

       [[ 8,  9, 10, 11],
        [20, 21, 22, 23]]])

In [84]:
transposed = ndarr3.transpose(0, 2, 1)
# x와 y축 바꾸기
# shape: (2, 3, 4)
transposed

array([[[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]],

       [[12, 16, 20],
        [13, 17, 21],
        [14, 18, 22],
        [15, 19, 23]]])

In [ ]:
# 요약 : 3차원 배열 transpose 는 shape 이 어떻게 바뀌는지 알아야 합니다.
#        transpose 결과 배열은 참고만 하세요.

- 데이터 자체는 바뀌지 않음: 메모리 상의 값은 그대로이고, 보는 관점만 바뀌는 것.

- 고차원 배열에서 매우 중요: 특히 이미지 처리(CNN), 시계열 분석(RNN), 행렬 연산 등에서 자주 사용됨.

- 축 번호는 0부터 시작: 예를 들어 (batch, channel, height, width) 구조에서 transpose(0, 2, 3, 1)은 채널을 마지막으로 이동시킴.
  + height 는 이미지의 세로
  + width 는 이미지의 가로
  + channel 는 이미지의 r,g,b
  + batch 는 이미지의 갯수